// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgbbcnxwfrxzthdylmkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnYmJjbnh3ZnJ4enRoZHlsbWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjgwOTksImV4cCI6MjA2MjY0NDA5OX0.JR699wKJVkSzoY09InGSvOJUuH0biKO6RuPl8kllygY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);